services:
  nextjs:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    networks:
      - lis-server_app_net
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/public/uploads
    restart: unless-stopped

networks:
  lis-server_app_net:
    external: true

volumes:
  uploads: